### ISSUE TITLE
500 error on lists route failing on prod

### ISSUE THREAD

**Issue by karlcow** [mozilla/trexa-service#10]
related to #5 

Just following the instructions here in the README

```
(env) ~/code/trexa-service % FLASK_APP=trexa flask run --host=0.0.0.0
 * Serving Flask app "trexa"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Jun/2020 10:01:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2020 10:01:27] "GET /favicon.ico HTTP/1.1" 404 -
[2020-06-08 10:02:01,263] ERROR in app: Exception on /lists [GET]
Traceback (most recent call last):
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/trexa-service/trexa/__init__.py", line 37, in show_downloads
    files = os.listdir(app.config['FINAL_LIST_DEST'])
FileNotFoundError: [Errno 2] No such file or directory: 'trexa/static/lists'
127.0.0.1 - - [08/Jun/2020 10:02:01] "GET /lists HTTP/1.1" 500 -
127.0.0.1 - - [08/Jun/2020 10:04:02] "GET /lists/trexa-2020-05-21.csv HTTP/1.1" 404 -
127.0.0.1 - - [08/Jun/2020 10:04:24] "GET /api/lists/2020-05-21?count=N HTTP/1.1" 404 -
```

So there's a 500 error on the lists route.

**Comment by karlcow** [comment]
same errors for dev environment.

```
(env) ~/code/trexa-service % FLASK_ENV=development FLASK_APP=trexa flask run
 * Serving Flask app "trexa" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with fsevents reloader
 * Debugger is active!
 * Debugger PIN: 191-981-503
127.0.0.1 - - [08/Jun/2020 10:06:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2020 10:06:16] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [08/Jun/2020 10:06:25] "GET /lists HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karl/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/trexa-service/trexa/__init__.py", line 37, in show_downloads
    files = os.listdir(app.config['FINAL_LIST_DEST'])
FileNotFoundError: [Errno 2] No such file or directory: 'trexa/static/lists'
127.0.0.1 - - [08/Jun/2020 10:06:25] "GET /lists?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2020 10:06:25] "GET /lists?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2020 10:06:25] "GET /lists?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2020 10:06:25] "GET /lists?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2020 10:06:25] "GET /lists?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2020 10:06:25] "GET /lists?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

```

**Comment by karlcow** [comment]
if the config doesn't exist.

https://github.com/mozilla/trexa-service/blob/1105042293e5424dfe97bb9e7f8ce1e96261e9db/trexa/__init__.py#L34-L38

This explodes… You need to either create a config or make a way for routes to fail gracefully with a `Configs are not defined` see the readme on how to set it up.
